[SW][Transformers-nuv] configure debug port mode         Sympton/Reason:                 The bios message cannot output via COM1(Debug Port).
            Root Cause:
                The debug port mode need set to 0.

            Solution/Change:
                [nuvoton-npcm750-buv-runbmc.dts]
                   -set idle-states:0

            Entry Test:
                Can get these message via debug port when bios boot:

                Copyright(c) 2021 American Megatrends International, LLC.
                PROGRESS CODE: V00061000 I0
                0x19 : Pre-memory SB Initialization.
                PROGRESS CODE: V03021001 I0
                0x4F : DXE IPL Start
                ERROR: Class:0; Subclass:20000; Operation: 1002
                ERROR: Class:0; Subclass:20000; Operation: 1000
                0x68 : PCI HB Initialization.
                0x70 : SB DXE Initialization.
                0x91 : Connecting Drivers.
                0x92 : PCI Bus Initialization.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x94 : PCI Bus Enumeration.
                0x95 : PCI Bus Request Resources.
                0x96 : PCI Bus Assign Resources.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x92 : PCI Bus Initialization.
                0x99 : SIO Initialization.