[Transformers][SW] Inventec OEM password random generation
    Symptom/Reason :
        - Generated random password for specified user HostAutoFW and HostAutoOS

    Root Cause:
        - N/A

    Solution/Change:
        [inv-ipmi-oem]
            - Manage user HostAutoUser and HostAutoOS in the openbmc ipmi user database
                -- create user with user id 14 and 15
                -- delete user account from openbmc user database
                -- delete the ipmi session belong to host interface when delete user account
            - check if the Host Interface usb0 is connected
            - check if the watchdog is enable and in the BIOSFBR2 state

    Entry Test:

        - TEST: When watch dog CurrentTimerUse is not in BIOSFRB2, the oem command run failed

            -- busctl get-property xyz.openbmc_project.Watchdog /xyz/openbmc_project/watchdog/host0 xyz.openbmc_project.State.Watchdog Enabled b false
            -- busctl get-property xyz.openbmc_project.Watchdog /xyz/openbmc_project/watchdog/host0 xyz.openbmc_project.State.Watchdog CurrentTimerUse s "xyz.openbmc_project.State.Watchdog.TimerUse.Reserved"

            -- ipmitool raw 0x3a 0x5d 1 0
            > Unable to send RAW command (channel=0x0 netfn=0x3a lun=0x0 cmd=0x5d rsp=0xd5): Command not supported in present state

        - TEST: When watch dog CurrentTimerUse is in BIOSFRB2, the oem command will run watchdog in BIOSFRB2 state

            -- busctl set-property xyz.openbmc_project.Watchdog /xyz/openbmc_project/watchdog/host0 xyz.openbmc_project.State.Watchdog CurrentTimerUse s "xyz.openbmc_project.State.Watchdog.TimerUse.BIOSFRB2"
            -- busctl set-property xyz.openbmc_project.Watchdog /xyz/openbmc_project/watchdog/host0 xyz.openbmc_project.State.Watchdog Enabled b true

        - TEST :create user HostAutoFW and HostAutoOS
            -- ipmitool raw 0x3a 0x5d 1 0
                0a 14 48 6f 73 74 41 75 74 6f 46 57 74 52 72 45
                63 4e 46 4e 4e 32 73 59 36 58 38 66 57 41 42 4c
                //HostAutoFWtRrEcNFNN2sY6X8fWABL

            -- ipmitool raw 0x3a 0x5d 2 0
                0a 14 48 6f 73 74 41 75 74 6f 4f 53 6d 56 76 32
                54 6f 31 67 71 5a 6f 49 6b 73 61 74 4a 75 68 31
                //HostAutoOSmVv2To1gqZoIksatJuh1

            --  ipmitool user list 1
                ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
                1   admin            false   true       true       ADMINISTRATOR
                2   root             false   true       true       ADMINISTRATOR
                3   sysadmin         false   true       true       ADMINISTRATOR
                4                    true    false      false      NO ACCESS
                5                    true    false      false      NO ACCESS
                6                    true    false      false      NO ACCESS
                7                    true    false      false      NO ACCESS
                8                    true    false      false      NO ACCESS
                9                    true    false      false      NO ACCESS
                10                   true    false      false      NO ACCESS
                11                   true    false      false      NO ACCESS
                12                   true    false      false      NO ACCESS
                13                   true    false      false      NO ACCESS
                14  HostAutoOS       false   true       true       ADMINISTRATOR
                15  HostAutoFW       false   true       true       ADMINISTRATOR

        - Test if the generated password is OK
            -- ipmitool user test 14 20 mVv2To1gqZoIksatJuh1
                Success
            -- ipmitool user test 15 20 tRrEcNFNN2sY6X8fWABL
                Success

        - TEST login by the HostAutoFW user with random generated password by RMCP+
            -- ipmitool -I lanplus -C17 -H 10.6.141.170 -p 623 -U HostAutoFW -P tRrEcNFNN2sY6X8fWABL shell
                ipmitool> mc watchdog get
                Watchdog Timer Use:     BIOS FRB2 (0x01)
                Watchdog Timer Is:      Stopped
                Watchdog Timer Actions: Hard Reset (0x01)
                Pre-timeout interval:   0 seconds
                Timer Expiration Flags: 0x02
                Initial Countdown:      30 sec
                Present Countdown:      0 sec

        - TEST the HostAutoFW can use openbmc web UI
            -- The user can login to the web ui and get information

        - TEST destory delete the user account
            -- ipmitool raw 0x3a 0x5d 4 0
            -- ipmitool raw 0x3a 0x5d 8 0
            -- ipmitool user list 1
            ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
            1   admin            false   true       true       ADMINISTRATOR
            2   root             false   true       true       ADMINISTRATOR
            3   sysadmin         false   true       true       ADMINISTRATOR
            4                    true    false      false      NO ACCESS
            5                    true    false      false      NO ACCESS
            6                    true    false      false      NO ACCESS
            7                    true    false      false      NO ACCESS
            8                    true    false      false      NO ACCESS
            9                    true    false      false      NO ACCESS
            10                   true    false      false      NO ACCESS
            11                   true    false      false      NO ACCESS
            12                   true    false      false      NO ACCESS
            13                   true    false      false      NO ACCESS
            14                   true    false      false      NO ACCESS
            15                   true    false      false      NO ACCESS

        - TEST if the HostAutoFW can login by RMCP+ after accounts delete
            -- ipmitool -I lanplus -C17 -H 172.17.0.2 -p 2623 -U HostAutoFW -P tRrEcNFNN2sY6X8fWABL shell
                Error: Unable to establish IPMI v2 / RMCP+ session

        - TEST User login web ui will failed

        - TEST : When the Host interface(usb0) is not enable, the oem command run failed
            -- busctl set-property xyz.openbmc_project.Network /xyz/openbmc_project/network/usb0 xyz.openbmc_project.Network.EthernetInterface NICEnabled b false

            -- ipmitool raw 0x3a 0x5d 1 0
            > Unable to send RAW command (channel=0x0 netfn=0x3a lun=0x0 cmd=0x5d rsp=0xd5): Command not supported in present state

        - TEST : When the Host interface(usb0) is not enable, the oem command run failed and
                the HostAutoFW and HostAutoOS will deleted if already existing in the system
            -- ipmitool raw 0x3a 0x5d 1 0
                 0a 14 48 6f 73 74 41 75 74 6f 46 57 75 78 6c 79
                 36 72 65 6e 37 46 57 76 76 62 36 45 6b 44 73 54
            -- ipmitool raw 0x3a 0x5d 2 0
                 0a 14 48 6f 73 74 41 75 74 6f 4f 53 6d 43 49 78
                 70 74 56 41 56 79 6e 55 61 67 6e 74 4f 39 48 65
            -- ipmitool user list 1
                ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
                1   admin            false   true       true       ADMINISTRATOR
                2   root             false   true       true       ADMINISTRATOR
                3   sysadmin         false   true       true       ADMINISTRATOR
                4                    true    false      false      NO ACCESS
                5                    true    false      false      NO ACCESS
                6                    true    false      false      NO ACCESS
                7                    true    false      false      NO ACCESS
                8                    true    false      false      NO ACCESS
                9                    true    false      false      NO ACCESS
                10                   true    false      false      NO ACCESS
                11                   true    false      false      NO ACCESS
                12                   true    false      false      NO ACCESS
                13                   true    false      false      NO ACCESS
                14  HostAutoOS       false   true       true       ADMINISTRATOR
                15  HostAutoFW       false   true       true       ADMINISTRATOR

            -- busctl set-property xyz.openbmc_project.Network /xyz/openbmc_project/network/usb0 xyz.openbmc_project.Network.EthernetInterface NICEnabled b false

            -- ipmitool raw 0x3a 0x5d 1 0
            Unable to send RAW command (channel=0x0 netfn=0x3a lun=0x0 cmd=0x5d rsp=0x85): Unknown (0x85)
            -- ipmitool user list 1
            ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
            1   admin            false   true       true       ADMINISTRATOR
            2   root             false   true       true       ADMINISTRATOR
            3   sysadmin         false   true       true       ADMINISTRATOR
            4                    true    false      false      NO ACCESS
            5                    true    false      false      NO ACCESS
            6                    true    false      false      NO ACCESS
            7                    true    false      false      NO ACCESS
            8                    true    false      false      NO ACCESS
            9                    true    false      false      NO ACCESS
            10                   true    false      false      NO ACCESS
            11                   true    false      false      NO ACCESS
            12                   true    false      false      NO ACCESS
            13                   true    false      false      NO ACCESS
            14                   true    false      false      NO ACCESS
            15                   true    false      false      NO ACCESS